version: "2.4"
services:
  cassandra:
    image: cassandra:3.11
    platform: linux/arm64/v8
    container_name: kong-tests-cassandra
    ports:
      - "9042:9042"

  postgres:
    build: ./postgres
    container_name: kong-tests-postgres
    command: postgres -c log_statement=all -c log_destination=stderr
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_HOST_AUTH_METHOD=trust"

  redis:
    image: redis
    container_name: kong-tests-redis
    ports:
      - "6379:6379"

  grpcbin:
    image: kong/grpcbin
    container_name: kong-tests-grpcbin
    ports:
      - "15002:9000"
      - "15003:9001"

  httpbin:
    image: kong/httpbin
    container_name: kong-tests-httpbin
    ports:
      - "8080:80"
