version: '3'

services:
  cassandra:
    image: "cassandra:${CASSANDRA_VERSION}"
    container_name: kong-tests-cassandra
    #    networks:
    #  - kong
    ports:
      - "9042:9042"

  postgres:
    build: ./postgres
    container_name: kong-tests-postgres
    #networks:
    #  - kong
    ports:
      - "5432:5432"

  redis:
    image: redis
    container_name: kong-tests-redis
    #networks:
    #  - kong
    ports:
      - "6379:6379"

        #networks:
  #  kong:
